### ISSUE TITLE
Feat : 채팅방 드래그 드랍으로 구현

### ISSUE THREAD

**Issue by LikeFireAndSky** [MOVIEJOJO7/cat-talk#19]
## Description
채팅방 삭제 기능을 드래그 드롭으로 구현 (삭제기능 추가)

## Todo

- [x] 드래그 드롭 작동하도록 수정
- [x] hello-dnd 설치
- [x] 드래그 시작하면 휴지통 영역 생성
