### ISSUE TITLE
Feat : 오픈 채팅방 검색 페이지 디자인

### ISSUE THREAD

**Issue by JitHoon** [MOVIEJOJO7/cat-talk#21]
## Description

search 페이지의 오픈 채팅방 검색 기능의 레이아웃을 디자인 할 예정입니다.

## Todo

- [ ] ShowAllOpenChat 컴포넌트 li 레이아웃 디자인
- [ ] OpenChatText 컴포넌트 레이아웃  디자인
- [ ] OpenChatPicture 컴포넌트 레이아웃  디자인
