### ISSUE TITLE
Feat : 오픈 채팅 검색 후 목록 클릭 시 모달 생성

### ISSUE THREAD

**Issue by JitHoon** [MOVIEJOJO7/cat-talk#22]
## Description

오픈 채팅 검색 후 목록 클릭 시 나타나는 모달 컴포넌트를 생성할 예정입니다.

## Todo

- [x] OpenChatModal 컴포넌트 구현
- [x] useCallback 사용 검토
- [x] 오픈 채팅방 목록명 추가
- [x] 뒤로 가기 버튼 추가
- [x] 취소 버튼 클릭 시, 다시 전체 목록을 띄워주기
