### ISSUE TITLE
Feat: Footer 추가, 로그아웃 기능 구현

### ISSUE THREAD

**Issue by syb0127** [MOVIEJOJO7/cat-talk#40]
## Description
Footer 와 로그아웃 기능을 구현하였습니다.

## Todo

- [ ] Footer 기능 구현
- [ ] Footer 간단한 디자인 
- [ ] 로그아웃 버튼 구현(푸터 안에 넣어놨습니다)

## ETC
없음
