### ISSUE TITLE
Feat : 소켓 통신을 이용한 유저 참여 정보 나타내기 (users)

### ISSUE THREAD

**Issue by TaePoong719** [MOVIEJOJO7/cat-talk#43]
## Description

민섭님과 의논한 사항들 금일까지 해결하겠습니다

## Todo

- [ ] 소켓 통신을 이용한 유저 참여 정보 나타내겠습니다.
- [ ] 이미지 소스 처리 로직 함수화
- [ ] searchmychat 페이지 채팅방 분류하기
