### ISSUE TITLE
Feat : private 톡방 나누기

### ISSUE THREAD

**Issue by LikeFireAndSky** [MOVIEJOJO7/cat-talk#46]
## Description
private 톡방 나누기

## Todo

- [ ] open 컴포넌트에서 분기
- [ ] private 도메인 제작
- [ ] 채팅방 눌렀을 때 링크 제작
