### ISSUE TITLE
Feat : 채팅방 분기, 개인, 단체 채팅방 분기

### ISSUE THREAD

**Issue by LikeFireAndSky** [MOVIEJOJO7/cat-talk#48]
## Description
채팅방 분기, 개인, 단체 채팅방 분기

## Todo

- [ ] Private 기준으로 채팅방 분기
- [ ] 개인, 단체 채팅방 분기
- [ ] Footer Icon 변경
