### ISSUE TITLE
Fix : Users, Search, ChatProfile, SearchMyChat 페이지 qa 작업 후 변경사항 수정

### ISSUE THREAD

**Issue by TaePoong719** [MOVIEJOJO7/cat-talk#62]
## Description

Users, Search, ChatProfile, SearchMyChat 페이지 qa 작업 결과물 수정

## Todo

- [ ] users : (스크롤 기능, 비동기 처리, image 유형 추가, 온라인인 상태 상단에 끌어올리기)
- [ ] search : (스크롤, 푸터 삽입)
- [ ] chatProfile : (제목/오픈채팅방 참여하기, image 함수 로직)
- [ ] searchmychat : (input 띄어쓰기 안들어가짐, 검색된 친구가 없을시 메시지, 채팅방이 없을 시 ‘현재 참여중인 채팅방이 없습니다’ => search page로 이동 , 스크롤, 이미지 Object-fit )
