### ISSUE TITLE
Fix : JoinPage DropZone 위치, 모양 변경

### ISSUE THREAD

**Issue by LikeFireAndSky** [MOVIEJOJO7/cat-talk#63]
## Description
Fix : DropZone 위치, 모양 변경

## Todo

- [ ] Dropzone안에 도형 삽입
- [ ] Dropzone안에 이미지 보여주기
- [ ] 로그인으로 돌아가기 버튼 추가
- [ ] Image 없을 때 로그인 불가 하도록 설정
